# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  lane :increment_build_number do
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "DeepLink.xcodeproj"
    )
  end
  lane :build do
    sync_code_signing(type: "appstore")
    setup_ci if ENV['CI']
    match(type: 'appstore')
    build_app(
      scheme: "DeepLink",
      silent: true,
      clean: true,
      export_method: "app-store", 
      archive_path: "./fastlane/archive/build",
      output_directory: "./fastlane/archive",
      output_name: "DeepLink.ipa",
      xcargs: "-allowProvisioningUpdates",
      include_bitcode: true
   ) 
   # upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  lane :upload_store do
    upload_to_testflight(
        skip_submission: true,
        skip_waiting_for_build_processing: true,
        wait_for_uploaded_build: false,
        ipa: "./fastlane/archive/DeepLink.ipa",
        username: "numanayhan@yandex.com",
        app_identifier: "com.hrdijital.deeplinks"
      )
    end
    lane :release  do

      increment_build_number
      build
      upload_store
    end 
end
